### PR TITLE
fix & docker-compose add

### PR DESCRIPTION
**Pull request by jlssmt**
added docker-compose.yaml
fixing #9

### CODE REVIEW

**Comment by jlssmt** [comment]
I dunno why, but LOCALE in docker-compose is not working...

**Review by JahFyahh — COMMENTED** [review]
I ran this and got the following output:

```
[+] Building 32.6s (7/9)                                                                                                                                                                       docker:default
 => [portfolio internal] load build definition from Dockerfile                                                                                                                                           0.1s
 => => transferring dockerfile: 1.43kB                                                                                                                                                                   0.0s
 => [portfolio internal] load .dockerignore                                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                                          0.0s
 => [portfolio internal] load metadata for docker.io/jlesage/baseimage-gui:alpine-3.12-glibc-v3                                                                                                          1.7s
 => [portfolio base 1/2] FROM docker.io/jlesage/baseimage-gui:alpine-3.12-glibc-v3@sha256:c95d616307cfc52a27324fa048ecca05426df791dd07491d401e0456f3afe2aa                                               8.6s
 => => resolve docker.io/jlesage/baseimage-gui:alpine-3.12-glibc-v3@sha256:c95d616307cfc52a27324fa048ecca05426df791dd07491d401e0456f3afe2aa                                                              0.0s
 => => sha256:c95d616307cfc52a27324fa048ecca05426df791dd07491d401e0456f3afe2aa 3.68kB / 3.68kB                                                                                                           0.0s
 => => sha256:ef1d619b81e9d0ddea354ce447bb35ce165a5ec17ac42074c4f01930cf2e4339 4.11MB / 4.11MB                                                                                                           0.8s
 => => sha256:4f57fa13a68446f6a7ac5330115bb49565dee372c2a66cd6879a4e6ff16dfe30 31.89kB / 31.89kB                                                                                                         0.0s
 => => sha256:c7251f0b0db04c7023b3f9c792fad7279c33cc7620a42833ec57c7282d804f81 1.53kB / 1.53kB                                                                                                           0.4s
 => => sha256:8572bc8fb8a32061648dd183b2c0451c82be1bd053a4ea8fae991436b92faebb 2.81MB / 2.81MB                                                                                                           1.0s
 => => sha256:f12e5e28197cb736112c2c79056377689f878daff748a442a90509a92539aadf 1.89MB / 1.89MB                                                                                                           1.4s
 => => sha256:6188e86cfb87496af68f10f645309b5daec574e35836b1e320f94c299fc84c9e 1.19MB / 1.19MB                                                                                                           1.2s
 => => extracting sha256:8572bc8fb8a32061648dd183b2c0451c82be1bd053a4ea8fae991436b92faebb                                                                                                                0.3s
 => => sha256:1a9487cdd4804b81b6476d03a74c20986f61cdae760577f1098ba8160e015073 1.02kB / 1.02kB                                                                                                           1.2s
 => => sha256:b0dd0e6f84f085ec81c7bc9433a21ca3a34f157cfaa3d6b908671de10976e875 1.02MB / 1.02MB                                                                                                           1.6s
 => => sha256:352508f1af9e48ef11271da257e235991efef83a66824e72f091db61bcd3c72f 4.93kB / 4.93kB                                                                                                           1.5s
 => => sha256:8b1a28625a77b30032e7390d1b36aa9d1476b8e3130963f2ab7bc7999dc664bf 239.15kB / 239.15kB                                                                                                       1.6s
 => => extracting sha256:c7251f0b0db04c7023b3f9c792fad7279c33cc7620a42833ec57c7282d804f81                                                                                                                0.0s
 => => sha256:8c43d5237e2003e2965607df6aed776378959e69ca0af567f020cef278eb8e2a 23.32MB / 23.32MB                                                                                                         4.5s
 => => extracting sha256:ef1d619b81e9d0ddea354ce447bb35ce165a5ec17ac42074c4f01930cf2e4339                                                                                                                0.5s
 => => sha256:3afd875ef9e50ff364c48a1651e1943e423cf40f2b8e063c993e7bd196493944 1.08MB / 1.08MB                                                                                                           2.3s
 => => sha256:f9f8142b8099fe0205a485a4c1c07504e66eae9919f57a86898c03fa5d7cba0c 536.40kB / 536.40kB                                                                                                       2.0s
 => => sha256:811abfb08666e160690afd06bbfc3b8e47a17aa9f4ea238726119b67e477f32e 32.65kB / 32.65kB                                                                                                         2.1s
 => => extracting sha256:f12e5e28197cb736112c2c79056377689f878daff748a442a90509a92539aadf                                                                                                                0.4s
 => => sha256:c703a2cf4918ec326d034456bc2bdd888ce0762eb1327309ff5a743c1eb1dc28 2.82kB / 2.82kB                                                                                                           2.4s
 => => sha256:93f6b87b49ec62cf09890ee63e23ec7dc97bde5e8829e30b61e03efca2f99f11 226.23kB / 226.23kB                                                                                                       2.8s
 => => sha256:61361933ae7f4d613f131837a6197476d4903fc82d5e6e279cf021a7df6d43d2 368.12kB / 368.12kB                                                                                                       2.8s
 => => extracting sha256:6188e86cfb87496af68f10f645309b5daec574e35836b1e320f94c299fc84c9e                                                                                                                0.7s
 => => extracting sha256:1a9487cdd4804b81b6476d03a74c20986f61cdae760577f1098ba8160e015073                                                                                                                0.0s
 => => extracting sha256:352508f1af9e48ef11271da257e235991efef83a66824e72f091db61bcd3c72f                                                                                                                0.0s
 => => extracting sha256:b0dd0e6f84f085ec81c7bc9433a21ca3a34f157cfaa3d6b908671de10976e875                                                                                                                0.1s
 => => extracting sha256:8b1a28625a77b30032e7390d1b36aa9d1476b8e3130963f2ab7bc7999dc664bf                                                                                                                0.0s
 => => extracting sha256:8c43d5237e2003e2965607df6aed776378959e69ca0af567f020cef278eb8e2a                                                                                                                2.6s
 => => extracting sha256:3afd875ef9e50ff364c48a1651e1943e423cf40f2b8e063c993e7bd196493944                                                                                                                0.1s
 => => extracting sha256:f9f8142b8099fe0205a485a4c1c07504e66eae9919f57a86898c03fa5d7cba0c                                                                                                                0.0s
 => => extracting sha256:811abfb08666e160690afd06bbfc3b8e47a17aa9f4ea238726119b67e477f32e                                                                                                                0.0s
 => => extracting sha256:c703a2cf4918ec326d034456bc2bdd888ce0762eb1327309ff5a743c1eb1dc28                                                                                                                0.0s
 => => extracting sha256:93f6b87b49ec62cf09890ee63e23ec7dc97bde5e8829e30b61e03efca2f99f11                                                                                                                0.0s
 => => extracting sha256:61361933ae7f4d613f131837a6197476d4903fc82d5e6e279cf021a7df6d43d2                                                                                                                0.0s
 => [portfolio internal] load build context                                                                                                                                                              0.0s
 => => transferring context: 65B                                                                                                                                                                         0.0s
 => [portfolio base 2/2] RUN apk --no-cache add ca-certificates wget curl && update-ca-certificates &&     add-pkg   openjdk11-jre   gtk+3.0   dbus-x11   dbus   webkit2gtk                             20.0s
 => ERROR [portfolio app 1/3] RUN EXPORT VERSION=${VERSION:-$(curl --silent "https://api.github.com/repos/buchen/portfolio/releases/latest" |grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')} &&  cd  2.1s
------
 > [portfolio app 1/3] RUN      EXPORT VERSION=${VERSION:-$(curl --silent "https://api.github.com/repos/buchen/portfolio/releases/latest" |grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')} &&       cd /opt && wget https://github.com/buchen/portfolio/releases/download/${VERSION}/PortfolioPerformance-${VERSION}-linux.gtk.x86_64.tar.gz &&   tar xvzf PortfolioPerformance-${VERSION}-linux.gtk.x86_64.tar.gz &&  rm PortfolioPerformance-${VERSION}-linux.gtk.x86_64.tar.gz:
1.032 --2023-12-06 18:21:46--  https://github.com/buchen/portfolio/releases/download//PortfolioPerformance--linux.gtk.x86_64.tar.gz
1.105 Resolving github.com (github.com)... 140.82.121.4
1.113 Connecting to github.com (github.com)|140.82.121.4|:443... connected.
1.157 HTTP request sent, awaiting response... 301 Moved Permanently
1.328 Location: https://github.com/portfolio-performance/portfolio/releases/download/PortfolioPerformance--linux.gtk.x86_64.tar.gz [following]
1.329 --2023-12-06 18:21:46--  https://github.com/portfolio-performance/portfolio/releases/download/PortfolioPerformance--linux.gtk.x86_64.tar.gz
1.329 Reusing existing connection to github.com:443.
1.329 HTTP request sent, awaiting response... 404 Not Found
1.498 2023-12-06 18:21:47 ERROR 404: Not Found.
1.498
------
failed to solve: process "/bin/sh -c export VERSION=${VERSION:-$(curl --silent \"https://api.github.com/repos/buchen/portfolio/releases/latest\" |grep '\"tag_name\":' | sed -E 's/.*\"([^\"]+)\".*/\\1/')} && \tcd /opt && wget https://github.com/buchen/portfolio/releases/download/${VERSION}/PortfolioPerformance-${VERSION}-linux.gtk.x86_64.tar.gz && \ttar xvzf PortfolioPerformance-${VERSION}-linux.gtk.x86_64.tar.gz && \trm PortfolioPerformance-${VERSION}-linux.gtk.x86_64.tar.gz" did not complete successfully: exit code: 8

```

**Comment by jlssmt** [comment]
you have to change URL in Dockerfile
I have no interest in updating my PR if the project owner is inactive.

**Comment by JahFyahh** [comment]
> I have no interest in updating my PR if the project owner is inactive.

Understandable, thank you for your efforts

**Comment by devben-io** [comment]
Hi guys,
Sorry for not being so responsive. (I have not been actively watching the project) 🙈
Thank you @jlssmt for raising this PR and already providing the docker-compose file. 
I'll have a look as soon as possible.

**Review by devben-io — APPROVED** [review]

**Comment by jlssmt** [comment]
@JahFyahh you can try this: https://github.com/quallenbezwinger/portfolio-performance-image
It's running on my side.

**Pull request merged**
